stage: production
stackName: chip-n-scale
region: us-east-1
bucket: your-bucket # existing s3 bucket to store deployment artifacts

tags:
  project: name-of-project

# This will be use to retrieve VPC and RDS informations
inferenceStack: inference-backend-production-us-east-1

lambda:
  runtime: python3.7
  handler: app.handler
  timeout: 60
  memory: 512
  concurrent: 5
  envs:
    # REQUIRED
    DATABASE_URL: ${cf:${self.inferenceStack}.dbConnectionString}
    PREDICTION_ENDPOINT: ${cf:${self.inferenceStack}.ELBEndpoint}
    # CUSTOM
    TILE_ACCESS_TOKEN: '{TILE_ACCESS_TOKEN}'
    TILE_ENDPOINT: 'https://example.com/{}/{}/{}.jpg?access_token={}'

sqs:
  maxReceiveCount: 5
